#---
kind: pipeline
type: docker
name: default

steps:
  - name: backend
    image: 438577872/hugo
    pull: if-not-exists # 跳过重复下载
    volumes:
      - name: html
        path: /data
#    environment:
#      GOPROXY: https://goproxy.cn
#      CGO_ENABLED: 0

    commands:
      - hugo
      - rm -rf /data/html
      - mv ./public /data/html

volumes:
  - name: html
    host:
      path: /docker/hugo/data
