#---
kind: pipeline
type: docker
name: default


clone:
  depth: 1

# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
steps:
  - name: backend
    image: 438577872/hugo
    pull: if-not-exists # 跳过重复下载
    volumes:
      - name: html
        path: /data
#    environment:
#      GOPROXY: https://goproxy.cn
#      CGO_ENABLED: 0

    commands:
      - hugo --minify
      - rm -rf /data/html
      - mv ./public /data/html
      - ls /data/
      - cp -r /data/s /data/html/s

volumes:
  - name: html
    host:
      path: /docker/hugo/data


